### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by cybercamphackathon** [martapastor/NACC#2]
* [x] There's no need to install electron system wide
* [x] Add electron in the package.json, so just running `npm install` will be enough
* [x] Add run instructions (`$(npm bin)/electron .`)
* [x] Missing archivo.html
* [x] Entrypoint for electron is expected to be index.js... main.js is overriden in the package.json which is not really necessary

**Comment by martapastor** [comment]
Fixed minor errors by renaming archivo.html call and main.js

**Comment by martapastor** [comment]
Updated README.md
